### ISSUE TITLE
nsp 파일의 수정 반영, ES6의 지원

### ISSUE THREAD

**Issue by tgyou** [Hanul/NSP#14]
안녕하세요.

nsp 를 사용해보고 있습니다,

브라우저로 nsp 를 열람 후, 코드를 수정 했습니다.
그런데 브라우저에서는 수정전의 결과만 표시되고 있는데,
서버를 재시작하지 않고, 반영할 수 있는 방법이 없을까요?

그리고,
nsp 내에서 es6등 babel preset 을 활용할 수 있다면 좋을 것 같습니다.

좋은 아이디어 감사드립니다.

**Comment by Hanul** [comment]
감사합니다.
nsp는 운영체제에서 지원하는 파일의 수정 시간을 감지하여 수정이 된 경우 새로 컴파일하는 구조를 갖고 있습니다.
실례가 안된다면 운영체제가 무엇인지, 사용하시는 node.js의 버전은 몇인지 제가 알 수 있을까요?

**Comment by Hanul** [comment]
또한 이미 Node.js가 ES6을 완벽하게 지원하는 바, Babel이 어떤 방식으로 사용되면 좋을지도 여쭈어봅니다.

**Comment by tgyou** [comment]
@Hanul 
안녕하세요. 

ES6 는 먼저 시도를 해보지 않았는데, 매번 es6 사용시 babel-node 로 사용을 했던터라, 
기본으로 된다고 인식을 두지 못했습니다. (_ _ )

ES6 코드를 테스트해본다고 www/index.nsp 를 수정했는데, 
역시 reload 를 해도 반응이 없어서, 데몬을 재시작하고나니 적용이 되었습니다. 

그 후 다시 수정을 하고 저장을 하니 바로 반영이 되더군요.
어제 데몬을 띄우고 오늘 재시작하기전 프로세스까지는 파일 갱신을 못했던듯 합니다.
아마도 일시적인 현상이라고는 생각하지만, 혹시나 모르니 제 환경을 공유드립니다.
Mac OS X 10.11.5 / nvm 0.26.1 / node 5.11.0 / npm 3.8.6

다시 한번 감사드립니다.

**Comment by tgyou** [comment]
ES6 를 테스트하던 도중 요청이 있어서 다시 open 하게 되었습니다.

1. 
Class 를 사용할 경우, `SyntaxError: Unexpected token class` 라고 에러를 뱉고, 데몬이 재시작을 하게 됩니다.
(node 6.x 대부터 지원)

2. 
또한 `let` 사용시 `SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` 라는 에러와 함께 데몬이 재시작하게 되는데,
`let` 이외 `const`, `function` 의 경우 별 탈없이 작성이 되네요. 

3. 
별도의 코드를 분리하여 include 가 아닌 import/require 로 사용할 수는 없을까요? import 사용시는 데몬 재시작, require 의 경우 없는 ReferenceError: require is not defined 라고 debug 로 노출이 됩니다.

일단 말씀하신 대로 node v8 harmony 지원이 있긴하나, 
node 버전별로 지원 범위가 달라서 애매하네요. https://kangax.github.io/compat-table/es6/
대안으로 babel/traceur 등의 transpiler 의 지원이 있다면 좋긴할 것 같습니다.

당장의 큰 이슈는 아니라서, 추후 검토 해주시면 감사하겠습니다.

**Comment by Hanul** [comment]
@tgyou 제가 Node 최신 버전인 6.2.1을 쓰고 있어서, 말씀하신 오류는 확인할 수가 없었습니다. 혹시 Node.js를 최신 버전으로 쓸 수 없는 환경에서 사용하시는 것인지 여쭈어 봅니다.

또한 3번의 경우에는 기능 추가하여 업데이트 하겠습니다. :)

**Comment by tgyou** [comment]
최신버전으로 사용하면 해결은 가능할것으로 보입니다. 
다만 node최신버전에서 일부 npm package들이 제대로 설치가 안되는 것들이 종종 있어서 최신을 사용하지 못하고 있습니다.

**Comment by Hanul** [comment]
NSP에서 `require` 함수를 사용할 수 있게 하였으며, Babel을 적용하였습니다. repository를 다운로드 하시어 테스트를 부탁드려도 될까요? 안정적으로 작동되는것을 확인하면 release로 배포하겠습니다.

**Comment by Hanul** [comment]
다른 분의 요청에 의하여, 일단 2.1로 배포를 하였습니다. 확인을 부탁드립니다.

**Comment by tgyou** [comment]
저도 방금 확인했습니다.
제대로 동작하는것도 확인했습니다.
감사합니다.

**Comment by Hanul** [comment]
감사합니다.
