### ISSUE TITLE
connection pool

### ISSUE THREAD

**Issue by kenlo88** [Hanul/NSP#15]
Is it possible to use a mysql connection pool?

I have an include file that pass the connection as self.conn to index.nsp, but self.conn.query is not recognised in index.nsp.

**Comment by Hanul** [comment]
what's node module for control mysql you are using now? :)

**Comment by kenlo88** [comment]
node-mysql

I have figured out the connection.nsp as (not connection pool yet, but it works)

```
var mysql = require('mysql');
var db = null;
module.exports = function () {
    if(!db) {
            db = mysql.createConnection({
            host : 'localhost',
            user : 'user',
            password : 'passwd',
            database : 'mydb'
        });
    }
    return db;
};
```

**Comment by Hanul** [comment]
check this out! :) https://github.com/Hanul/nsp-sample-bbs-mysql/blob/master/www/index.nsp
